import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiRouterRouter from "./ai-router";
import pluginsRouter from "./plugins";
import memoryRouter from "./memory";
import systemRouter from "./system";
import commandsRouter from "./commands";
import devicesRouter from "./devices";
import eventsRouter from "./events";
import ucmRouter from "./ucm";
import goalsRouter from "./goals";
import feedbackRouter from "./feedback";
import predictionsRouter from "./predictions";
import autonomyRouter from "./autonomy";
import traceRouter from "./trace";
import chatRouter from "./chat";
import chatStreamRouter from "./chat-stream";
import presenceRouter from "./presence";
import visionRouter from "./vision";
import whatsappRouter from "./whatsapp";
import locationRouter from "./location";
import discoveryRouter from "./discovery";
import personaRouter from "./persona";
import routinesRouter from "./routines";
import notificationsRouter from "./notifications";
import briefingsRouter from "./briefings";
import configRouter from "./config";
import storeRouter from "./store";
import channelsRouter from "./channels";
import adminRouter from "./admin";
import openclawRouter from "./openclaw";
import lieDetectorRouter from "./lie-detector";
import pairingRouter from "./pairing";
import powerRouter from "./power";
import snarkRouter from "./snark";
import brainRouter from "./brain";
import analyticsRouter from "./analytics";
import providersRouter from "./providers";
import genesisRouter from "./genesis";
import capabilitiesRouter from "./capabilities";
import bodyRouter from "./body";
import faceRouter from "./face";
import halTestRouter from "./hal-test";
import systemNetRouter from "./system-net";
import agentRouter from "./agent";
import diagRouter from "./diag";
import voiceRouter from "./voice";
import showsRouter from "./shows";
import provisionRouter from "./provision";
import youtubeRouter from "./youtube";

const router: IRouter = Router();

router.use(chatRouter);
router.use("/chat", chatStreamRouter);
router.use(healthRouter);
router.use(aiRouterRouter);
router.use(pluginsRouter);
router.use(memoryRouter);
router.use(systemRouter);
router.use(commandsRouter);
router.use(personaRouter);
router.use(discoveryRouter);
router.use(devicesRouter);
router.use(eventsRouter);
router.use(ucmRouter);
router.use(goalsRouter);
router.use(feedbackRouter);
router.use(predictionsRouter);
router.use(autonomyRouter);
router.use(traceRouter);
router.use("/presence", presenceRouter);
router.use("/vision", visionRouter);
router.use(whatsappRouter);
router.use(locationRouter);
router.use(routinesRouter);
router.use(notificationsRouter);
router.use(briefingsRouter);
router.use(configRouter);
router.use(storeRouter);
router.use(channelsRouter);
router.use(adminRouter);
router.use(openclawRouter);
router.use(lieDetectorRouter);
router.use(pairingRouter);
router.use(powerRouter);
router.use(snarkRouter);
router.use(brainRouter);
router.use(analyticsRouter);
router.use("/providers", providersRouter);
router.use("/genesis", genesisRouter);
router.use(capabilitiesRouter);
router.use(bodyRouter);
router.use(faceRouter);
router.use(halTestRouter);
router.use(systemNetRouter);
router.use(agentRouter);
router.use(diagRouter);
router.use(voiceRouter);
router.use(showsRouter);
router.use(provisionRouter);
router.use(youtubeRouter);

export default router;
